[package]
name = "anyleaf_usb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# usbd-serial = "^0.1.1"
num_enum = { version = "^0.7.0", default_features = false }