[package]
name = "anyleaf_usb"
version = "0.1.0"
edition = "2024"


[dependencies]
num_enum = { version = "^0.7.3", default-features = false }


hal = { package = "stm32-hal2", path = "../../stm32-hal", optional = true }
usb-device = "0.3.2"
usbd-serial = { version = "0.2.2", optional = true }
defmt = { version = "1.0.1", optional = true }

[features]
hal = ["defmt"]
hal_g431 = ["hal/g431", "usbd-serial", "hal"]
hal_g473 = ["hal/g473", "usbd-serial", "hal"]
hal_h7 = ["hal/h743v", "hal"] # todo: OTG